### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by jeroenooms** [mannau/h5#20]
Trying to compile with gcc 4.9.3 on windows:

```
* installing *source* package 'h5' ...
** package 'h5' successfully unpacked and MD5 sums checked
** libs
C:/Rtools/mingw64/bin/g++  -I"C:/PROGRA~1/R/R-EXPE~1/include" -DNDEBUG    -I"D:/rcpp_lib/Rcpp/include" -I"C:/Rbuild/R-devel-win64/extsoft/include"  -I"/include"/hdf5 -I"/include"/hdf5_cpp -I"/include"/hdf5_hl -I"/include"/hdf5_hl_cpp -I"/include"/cmakeconf   -O2 -Wall  -mtune=core2 -c Attribute.cpp -o Attribute.o
In file included from Attribute.cpp:1:0:
Attribute.h:1:19: fatal error: H5Cpp.h: No such file or directory
 #include <H5Cpp.h>
                   ^
compilation terminated.
make: *** [Attribute.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-EXPE~1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-EXPE~1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="h5.dll" WIN=64 TCLBIN=64 OBJECTS="Attribute.o Dataset.o Dataspace.o File.o Group.o Helpers.o RcppExports.o"' had status 2
C:/Rtools/mingw64/bin/g++  -I"C:/PROGRA~1/R/R-EXPE~1/include" -DNDEBUG    -I"D:/rcpp_lib/Rcpp/include" -I"C:/Rbuild/R-devel-win64/extsoft/include"  -I"/include"/hdf5 -I"/include"/hdf5_cpp -I"/include"/hdf5_hl -I"/include"/hdf5_hl_cpp -I"/include"/cmakeconf   -O2 -Wall  -mtune=core2 -c Attribute.cpp -o Attribute.o
In file included from Attribute.cpp:1:0:
Attribute.h:1:19: fatal error: H5Cpp.h: No such file or directory
 #include <H5Cpp.h>
                   ^
compilation terminated.
make: *** [Attribute.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-EXPE~1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-EXPE~1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="h5.dll" WIN=64 TCLBIN=64 OBJECTS="Attribute.o Dataset.o Dataspace.o File.o Group.o Helpers.o RcppExports.o" symbols.rds' had status 2
ERROR: compilation failed for package 'h5'
* removing 'D:/rcpp_check/h5.Rcheck/h5'
```

**Comment by jeroenooms** [comment]
Ah sorry i'm missing libhdf5 obviously.
